# Generated by Django 4.1.1 on 2022-10-18 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('git', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('avatar', models.ImageField(default='user.jpg', upload_to='users/avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('live_preview_link', models.URLField(blank=True, max_length=250, null=True)),
                ('source_code_link', models.URLField(blank=True, max_length=250, null=True)),
                ('cover_photo', models.ImageField(default='project.jpg', upload_to='projects/demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('down_vote', models.ManyToManyField(blank=True, null=True, related_name='programmer_down', to='base.programmer')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmer')),
                ('up_vote', models.ManyToManyField(blank=True, null=True, related_name='programmer_up', to='base.programmer')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BigIntegerField(default=0)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
        migrations.CreateModel(
            name='TechTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('level_of_mastery', models.CharField(blank=True, choices=[('Starter', 'Starter'), ('Basic', 'Basic'), ('Comfortable', 'Comfortable'), ('Skillfull', 'Skillfull'), ('Master', 'Master')], max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programmer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
    ]
